### ISSUE TITLE
有客户端或者网页嘛？

### ISSUE THREAD

**Issue by uiosun** [east-eden/server#6]
Windows系统能不能跑起来？有些软件好像是 *nix 专属

**Comment by hellodudu** [comment]
windows系统可以跑的，默认情况下没有用到其他的软件，客户端目前暂时只能用cli或者机器人

**Comment by uiosun** [comment]
Windows 是配上 WSL 吗？我去试试

**Comment by hellodudu** [comment]
> Windows 是配上 WSL 吗？我去试试

不用，debug模式下装了go和mongo就能跑，release模式下需要用到consul和nsq。

**Comment by uiosun** [comment]
Windows 下没有 syscall.Rlimit，直接报了 undefined

查到了这个：https://forum.golangbridge.org/t/how-can-i-use-syscall-kill-in-windows/11472

**Comment by uiosun** [comment]
WSL 里跑起来了，这是要对着代码玩吧哈哈，有些不懂这个游戏怎么玩。

**Comment by hellodudu** [comment]
> Windows 下没有 syscall.Rlimit，直接报了 undefined
> 
> 查到了这个：https://forum.golangbridge.org/t/how-can-i-use-syscall-kill-in-windows/11472

https://github.com/east-eden/server/commit/e3b833d7cc75d74a2e5d1ed899d0b047f38722b0

忘了加条件编译，最新dev版本修复了，另外这只是个服务器框架，包含一些基础的游戏逻辑，并不是完整的游戏哈。

**Comment by uiosun** [comment]
> 这只是个服务器框架，包含一些基础的游戏逻辑，并不是完整的游戏哈

所以我能够用这个框架写游戏？

最近公司裁员，我们部门 GG 了，想转 GoLang，决定做点什么当敲门砖

**Comment by hellodudu** [comment]
> > 这只是个服务器框架，包含一些基础的游戏逻辑，并不是完整的游戏哈
> 
> 所以我能够用这个框架写游戏？
> 
> 最近公司裁员，我们部门 GG 了，想转 GoLang，决定做点什么当敲门砖

当然，我现在的项目就是用这套框架：）

**Comment by uiosun** [comment]
大佬，探讨个问题：

打算做个 2D 游戏，玩家移动用 UDP，玩家操作用 TCP，是这样嘛？

考虑到 UDP 性能好，TCP 稳健

我看 stackoverflow 上有人用 TCP 直接把移动、操作都做了，会不会压力比较大？

**Comment by hellodudu** [comment]
> 大佬，探讨个问题：
> 
> 打算做个 2D 游戏，玩家移动用 UDP，玩家操作用 TCP，是这样嘛？
> 
> 考虑到 UDP 性能好，TCP 稳健
> 
> 我看 stackoverflow 上有人用 TCP 直接把移动、操作都做了，会不会压力比较大？

还是应该看具体场景，fps、moba这种对战实时性和延迟要求比较高的场景udp会合适一些，mmo的话tcp就足够了
